version: '3.8'
services:
  rails_api:
    image: rails_api
    build: .
    volumes: 
      - ./apps/todos-api:/var/app
    ports:
      - 3000:3000
    command: bash -c "rm -f tmp/pids/server.pid && cd var/app && bundle install && rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
      - complete-network

  postgres_db:
    image: postgres:latest
    ports:
        - 3432:5432
    volumes:
        - ./dbfiles:/docker-entrypoint-initdb.d
        - /var/lib/postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root
        POSTGRES_DB: railsDB
    networks:
      - complete-network   
        
  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    volumes:
      - /var/lib/pgadmin4/storage
    environment:
      PGADMIN_DEFAULT_EMAIL: "danicasa@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "qwerty"
    ports:
      - 80:80
    depends_on:
      - postgres_db   
    networks:
      - complete-network  

networks:
  complete-network:
    external: false

    