version: '3.8'
services:
  rails_app:
    image: my_rails_app
    build: .
    volumes: 
      - ./apps:/var/apps
    networks:
      - complete-network
  rails_api:
    image: my_rails_api
    build: .
    volumes: 
      - ./apps:/var/apps
    networks:
      - complete-network

  postgres_db:
    image: postgres:latest
    ports:
        - 3432:5432
    volumes:
        - ./dbfiles:/docker-entrypoint-initdb.d
        - /var/lib/postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root
        POSTGRES_DB: railsDB
    networks:
      - complete-network   
        
  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    volumes:
      - /var/lib/pgadmin4/storage
    environment:
      PGADMIN_DEFAULT_EMAIL: "danicasa@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "qwerty"
    ports:
      - 80:80
    depends_on:
      - postgres_db   
    networks:
      - complete-network  

networks:
  complete-network:
    external: false

    